cache:
  paths:
    - .cache

stages:
  - test
  - buildARM

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - go get gommo

test:
  stage: test
  tags:
    - shell
    - linux
  script:
    - make test

buildARM:
  stage: build
  tags:
    - shell
    - linux
  script:
    - make buildarm
  only:
  - master
