default:
  image: golang:1.19

  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
    - make build

deploy:
  script:
    - flyctl deploy
