image: golang:bookworm

cache:
  paths:
    - /apt-cache
    - .cache

stages:
  - test
  - buildARM

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - go get gommo

test:
  stage: test
  script:
    - make test

buildARM:
  stage: build
  script:
    - make buildarm
  only:
  - master
